services:
  
  catalogue:
     build: ./catalogue
     image: sri2890/catalogue:1.0.0
     container_name: catalogue
     depends_on: 
      - mongodb
  user:
     build: ./user
     image: sri2890/user:1.0.0
     container_name: user
     depends_on: 
      - redis
      - mongodb
  cart:
     build: ./cart
     image: sri2890/cart:1.0.0
     container_name: cart
     depends_on: 
      - redis
      - catalogue
  shipping:
     build: ./shipping
     image: sri2890/shipping:1.0.0
     container_name: shipping
     depends_on: 
      - mysql
      - cart
  payment:
     build: ./payment
     image: sri2890/payment:1.0.0
     environment:
       CART_HOST: "cart"
       CART_PORT: "8080"
       USER_HOST: "user"
       USER_PORT: "8080"
       AMQP_USER: roboshop
       AMQP_PASS: roboshop123
     container_name: payment
     depends_on:
      - rabbitmq 
      - cart
      - user

  frontend:
     build: ./frontend
     image: sri2890/frontend:1.0.0
     container_name: frontend
     ports:
     - "80:80"
     depends_on: 
      - catalogue
      - user
      - cart
      - shipping
      - payment
  mongodb:
     build: ./mongodb
     image: sri2890/mongodb:1.0.0
     container_name: mongodb
  redis:
    image: redis:7.0
    container_name: redis
  mysql:
     build: ./mysql
     image: sri2890/mysql:1.0.0
     container_name: mysql
     environment:
       MYSQL_ROOT_PASSWORD: RoboShop@1
  rabbitmq:
     image: rabbitmq:3
     environment:
       RABBITMQ_DEFAULT_USER: roboshop
       RABBITMQ_DEFAULT_PASS: roboshop123
     container_name: rabbitmq
   
networks:
  default:
    driver: bridge
    name: roboshop
    external: false
